version: "3.3"
services:
    app:
      image: sguide
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWD: example
        POSTGRES_HOST: db
      ports:
        - 3000:3000
      entrypoint: ["bin/entry.sh"]
      command:
       rails s -b 0.0.0.0
    db:
      image: postgres:alpine3.15 #intended for production use
      environment:
        POSTGRES_PASSWORD: example